name: testitest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-server:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy built server via SCP
      - uses: appleboy/scp-action@master

      - run: npm i
      - run: npm build

        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "./server/lib"
          target: "/home/simona/webapps/simplyshift/server"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          script: ls
