name: Build and deploy SimplyShift
on:
  push:
    branches:
      - master

jobs:
  build-server:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      - name: install dependencies
        run: |
          cd server
          npm i
          npm run build

      - name: deploy compiled server
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "./server/lib,./server/package.json"
          target: "/home/simona/webapps/simplyshift"

      - name: install server dependencies
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          script: cd /home/simona/webapps/simplyshift/server && npm install && pm2 restart simplyshift-server

  build-client:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      - name: build client
        run: |
          cd client
          printf "$ENV_PRODUCTION" >> .env.production
          cat .env.production
          npm i
          npm rebuild node-sass
          npm run build
        env:
          ENV_PRODUCTION: ${{secrets.ENV_PRODUCTION}}


      - name: deploy client
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "./client/.next,./client/package.json, ./client/package-lock.json"
          target: "/home/simona/webapps/simplyshift"

      - name: restart client
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          script: cd /home/simona/webapps/simplyshift/client && npm i && pm2 restart simplyshift-client