name: testitest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-server:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build the server
        run: |
          npm i
          npm build

      - name: List output files
        run: ls
#
#      - name: deploy built server
#        uses: appleboy/scp-action@master
#        env:
#          HOST: ${{ secrets.HOST }}
#          USERNAME: ${{ secrets.USERNAME }}
#          PORT: ${{ secrets.PORT }}
#          KEY: ${{ secrets.SSH_KEY }}


#        with:
#          source: "./server/lib"
#          target: "/home/simona/webapps/simplyshift/server"
#
#      - name: Executing remote command
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          USERNAME: ${{ secrets.USERNAME }}
#          PORT: ${{ secrets.PORT }}
#          KEY: ${{ secrets.SSH_KEY }}
#          script: ls
