name: testitest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-server:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: build the server
        run: |
          cd server
          npm i
          npm run build

      - name: deploy built server
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "./server/lib/"
          target: "/home/simona/webapps/simplyshift"

      - name: create environment file
        run: |
          cd server
          node lib/utils/create-environment-file.js > .env
          echo node lib/utils/create-environment-file.js

      - name: deploy environment file
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "./server/.env"
          target: "/home/simona/webapps/simplyshift"
