name: Build and deploy SimplyShift
on:
  push:
    branches:
      - master

jobs:
  build-server:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      - name: install dependencies
        run: |
          cd server
          npm i
          npm run build

      - name: create environment file
        run: |
          cd server
          printf "$ENV_SERVER_PRODUCTION" >> .env
        env:
          ENV_SERVER_PRODUCTION: ${{secrets.ENV_SERVER_PRODUCTION}}

      - name: delete old server
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          script: cd /home/simona/webapps/simplyshift && rm server -r

      - name: deploy compiled server
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "./server/lib,./server/package.json, ./server/package-lock.json, ./server/ormconfig.js, ./server/.env"
          target: "/home/simona/webapps/simplyshift"

      - name: install server dependencies and run database migrations
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          script: cd /home/simona/webapps/simplyshift/server && npm install && npm run migration:run && pm2 restart ss-server-4400

  build-client:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/client/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/client/package-lock.json') }}

      - name: build client
        run: |
          cd client
          printf "$ENV_PRODUCTION" >> .env.production
          npm i
          npm rebuild node-sass
          npm run build
        env:
          ENV_PRODUCTION: ${{secrets.ENV_PRODUCTION}}

      - name: delete old client
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          script: cd /home/simona/webapps/simplyshift && rm client -r

      - name: deploy client
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "./client/.next, ./client/package.json, ./client/public, ./client/package-lock.json"
          target: "/home/simona/webapps/simplyshift"

      - name: restart client
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          script: cd /home/simona/webapps/simplyshift/client && npm install && pm2 restart ss-client-3008
