name: Test SimplyShift
on:  [push]

jobs:
  test-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      - name: check client
        run: |
          cd client
          npm ci
          npm run lint

  test-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      - name: check server
        run: |
          cd server
          npm ci
          npm run lint


